'use strict';
/**
 * Apply all pending Drizzle migrations to the SQLite database.
 *
 * Run:  node scripts/migrate.js
 *
 * The migrations are generated by:  npm run generate   (drizzle-kit generate)
 * and live in ./drizzle/
 */
require('dotenv').config();
const path     = require('path');
const Database = require('better-sqlite3');
const { drizzle } = require('drizzle-orm/better-sqlite3');
const { migrate } = require('drizzle-orm/better-sqlite3/migrator');

const dbPath = path.resolve(__dirname, '../', process.env.DATABASE_URL || './db/dev.sqlite');

const sqlite = new Database(dbPath);
sqlite.pragma('journal_mode = WAL');
sqlite.pragma('foreign_keys = ON');

const db = drizzle(sqlite);

migrate(db, { migrationsFolder: path.resolve(__dirname, '../drizzle') });

console.log('✓ Migrations applied successfully');
sqlite.close();
